stages:
- test

build-fedora:
  image: fedora:latest
  stage: test
  before_script:
    - dnf install -y gcc redhat-rpm-config which gnome-common gtk3-devel
  script:
    - ./autogen.sh
    - make
    - make install

