stages:
- test

build-fedora:
  image: fedora:latest
  stage: test
  before_script:
    - dnf install -y gcc redhat-rpm-config which gettext-devel gnome-common make gtk3-devel
  script:
    - ./autogen.sh --disable-dependency-tracking
    - make
    - make install

